stages:
  - build
  - run

build:
  stage: build
  image: python:3.11
  before_script:
    - apt-get update
    - apt-get install -y gcc
  script:
    - python3 -m venv venv
    - ./venv/bin/pip install --upgrade pip
    - ./venv/bin/pip install -r requirements.txt
    - mkdir -p bin
    - gcc raj.c -o ./bin/bgmi
    - chmod +x ./bin/bgmi
  artifacts:
    paths:
      - bin/
      - venv/

run:
  stage: run
  image: python:3.11
  script:
    - ./bin/bgmi &
    - ./venv/bin/python a.py
